apiVersion: v1
kind: Service
metadata:
  name: sparkmaster
  namespace: {{ .Release.Name }}
spec:
  selector:
    app: sparkmaster
  ports:
  - port: {{ .Values.sparkmaster.fortyPort }}
    targetPort: 4040
    name: port-name
  - port: {{ .Values.sparkmaster.sixtyPort }}
    targetPort: 6066
    name: port-name-two
  - port: {{ .Values.sparkmaster.seventyPort }}
    targetPort: 7077
    name: port-name-three
  - port: {{ .Values.sparkmaster.eightyPort }}
    targetPort: 8080
    name: port-name-five
