apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparkmaster
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: sparkmaster 
  template: 
    metadata: 
      labels: 
        app: sparkmaster
    spec: 
      imagePullSecrets:
      {{- if .Values.requiredSecrets.intersystemsContainerRegistrySecret }}    
      - name: {{ .Values.requiredSecrets.intersystemsContainerRegistrySecret }}
      {{- end }}

      containers:
      - name: sparkmaster-container
        image: {{ .Values.image.registry }}/{{ .Values.image.repository }}/sparkmaster:{{ .Chart.AppVersion }}
        env:
        - name: SPARK_NODE_TYPE
          value: {{ .Values.sparkmaster.environment.sparkNodeType }}
        - name: SPARK_PUBLIC_DNS
          value: {{ .Values.sparkmaster.environment.sparkPublicDns }}
        - name: IRIS_MASTER_HOST
          value: {{ .Values.sparkmaster.environment.irisMasterHost }}
        - name: IRIS_MASTER_USERNAME
          value: {{ .Values.sparkmaster.environment.irisMasterUsername }}
        - name: IRIS_MASTER_PASSWORD
          value: {{ .Values.sparkmaster.environment.irisMasterPassword }}
        - name: IRIS_MASTER_NAMESPACE
          value: {{ .Values.sparkmaster.environment.irisMasterNamespace }}
       
        # resources:
        #   requests:
        #     cpu: {{ .Values.bankingCore.compute.cpu }}
        #     memory: {{ .Values.bankingCore.compute.memory }}
