apiVersion: v1
kind: Service
metadata:
  name: worker-portal
  namespace: {{ .Release.Name }}
spec:
  selector:
    app: worker
  ports:
  - port: {{ .Values.workers.webPort1 }}
    targetPort: 8081
    name: worker
