# Used to specify where the deployment is being done
# cloudProvider: "dev"
# cloudProviderRegion: "dev"
skaffold: false

skaffoldSparkImage: ""

image:
  registry: containers.intersystems.com/iscinternal/sds
  repository: irisdemo-base-spark-iris
  
# These are the secret fields needed to successfully deploy.
# They will be injected by the control plane:
requiredSecrets:
  irisLicense: ""
  intersystemsContainerRegistrySecret: ""

sparkmaster:
  fortyPort: 4040
  sixtyPort: 6066
  seventyPort: 7077
  eightyPort: 8080
  environment:
      sparkNodeType: "Master"
      sparkPublicDns: "localhost"
      irisMasterHost: "datalake" # DNS based on the name of the service!
      irisMasterUsername: "SuperUser"
      irisMasterPassword: "sys"
      irisMasterNamespace: "APP"
  compute:
      nodeTypeSelector: ""
      cpu: 2
      memory: 2Gi

workers:
  webPort1: 10010
  workerPort1: "10011"
  webPort2: 10012
  workerPort2: "10013"
  environment:
      sparkNodeType: "Worker"
      sparkWorkerCores: "1"
      sparkWorkerMemory: 1g
      sparkPublicDNS: localhost
  compute:
      nodeTypeSelector: ""
      cpu: 2
      memory: 2Gi

